_wandb:
    value:
        cli_version: 0.25.0
        e:
            ls107qilt11zkh4fuf93xl9f6docvc8r:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "3221225472"
                codePath: x_pred_next_scale.py
                codePathLocal: x_pred_next_scale.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "269880406016"
                email: titoduc1905@gmail.com
                executable: /Users/edgarduc/Code/basic_var/.venv/bin/python
                git:
                    commit: cb82496f2e5ed75b424a7058c89602fa4a959dde
                    remote: https://github.com/GAD-cell/basic_var.git
                host: MacBook-Air-de-Edgar.local
                memory:
                    total: "25769803776"
                os: macOS-15.4.1-arm64-arm-64bit
                program: /Users/edgarduc/Code/basic_var/x_pred_next_scale.py
                python: CPython 3.12.12
                root: /Users/edgarduc/Code/basic_var
                startedAt: "2026-02-18T10:05:18.855644Z"
                writerId: ls107qilt11zkh4fuf93xl9f6docvc8r
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
            "2":
                - 1
                - 11
                - 41
                - 49
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.12
            "5": 0.25.0
            "6": 5.1.0
            "12": 0.25.0
            "13": darwin-arm64
attn_l2_norm:
    value: true
batch_size:
    value: 32
ckpt_every_n_steps:
    value: 0
cond_drop_prob:
    value: 0.1
d_model:
    value: 128
decoder_type:
    value: var
device:
    value: mps
drop_path_rate:
    value: 0.05
dropout:
    value: 0
epochs:
    value: 1000
eval_every_n_epochs:
    value: 5
grad_accum:
    value: 1
input_noise_base:
    value: 0.05
input_noise_decay:
    value: 0.6
knn_k:
    value: 3
lr:
    value: 0.0003
mlp_ratio:
    value: 2
n_eval_samples:
    value: 5000
n_head:
    value: 4
n_layer:
    value: 4
noise_dim:
    value: 256
noise_scale:
    value: 1
num_classes:
    value: 10
patch_size:
    value: 4
real_features_path:
    value: data/cifar10_train_dinov2_features.pt
real_subset:
    value: 50000
scales:
    value:
        - 4
        - 8
        - 16
        - 32
shared_aln:
    value: false
train_data_path:
    value: data/
use_amp:
    value: false
use_noise_seed:
    value: false
use_wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: x_pred_next_scale
wandb_run_name:
    value: 20260218-110518-cifar10-var-L4-H4-d128-e1000
weight_decay:
    value: 0.0001
workers:
    value: 0
